version: '3.7'
services:
    nginx:
        container_name: ${COMPOSE_PROJECT_NAME}_nginx
        image: nginx:alpine
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./wordpress:/var/www/html
        ports:
            - '$WP_PORT:80'
        depends_on:
            - wordpress
        networks:
            - nuxt-network

    wordpress:
        container_name: ${COMPOSE_PROJECT_NAME}_wordpress
        image: wordpress:6.4.3-php8.1
        volumes:
            - ./wordpress:/var/www/html
        depends_on:
            - mysql
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_USER: $WP_MYSQL_USERNAME
            WORDPRESS_DB_PASSWORD: $WP_MYSQL_PASSWORD
            WORDPRESS_DB_NAME: $WP_MYSQL_DATABASE
            WORDPRESS_DEBUG: $WP_DEBUG
            WORDPRESS_CONFIG_EXTRA:
                define('WP_SITEURL', '$WP_URL');
                define('WP_HOME', '$WP_URL');
        networks:
            - nuxt-network

    phpmyadmin:
        container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
        image: phpmyadmin/phpmyadmin
        depends_on:
            - mysql
        environment:
            - PMA_HOST=mysql
            - PMA_ARBITRARY=1
            - UPLOAD_LIMIT=300M
        ports:
            - $WP_PORT_PHP_MY_ADMIN:80
        networks:
            - nuxt-network

    mysql:
        container_name: ${COMPOSE_PROJECT_NAME}_mysql-maria
        image: mariadb:10.5
        volumes: 
            - ./db/dev:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'false'  # 不允許空密碼
            MYSQL_ROOT_PASSWORD: $WP_MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: $WP_MYSQL_DATABASE
            MYSQL_USER: $WP_MYSQL_USERNAME   # 指定新的使用者
            MYSQL_PASSWORD: $WP_MYSQL_PASSWORD # 指定新使用者的密碼
        networks:
            - nuxt-network
networks:
    nuxt-network:
